 #pragma once
#include "ThirdPartyHeadersBegin.h"
#include <vector>
#include <boost/shared_ptr.hpp>
#include "ThirdPartyHeadersEnd.h"
#include "AltTecUtil.h"
#include "basicTypes.h"
#include "IJK.h"
namespace tecplot { namespace ___3933 { class FESubzonePartitionerInterface; class ___37; class PartitionTecUtilDecorator; class ___1881; class ___1350; class ItemSetIterator; class ZoneInfoCache { public: ZoneInfoCache( ___37*               ___36, ItemSetIterator&          zoneIter, ___1844 const&                maxIJKSubzoneSize, ___2090::ItemOffset_t feSubzoneSize, bool                      sortFENodesAndCells); boost::shared_ptr<___1881> getIJKZoneInfo( ___4636 zone, ___4636 ___341); boost::shared_ptr<___1881> getIJKZonePartitionInfo( ___4636 zone, ___4636 ___341, ___4636 ___2977); boost::shared_ptr<___1350> getFEZoneInfo( ___4636 zone, ___4636 ___341); boost::shared_ptr<___1350> getFEZonePartitionInfo( ___4636 zone, ___4636 ___341, ___4636 ___2977, PartitionTecUtilDecorator& partitionTecUtilDecorator); void remove( ___4636 zone, ___4636 ___341); void clear(); void replaceDataSource(___37* ___36); private: ___37*                                                ___2337; ___4636 const                                          m_numZones; ___1844 const                                                  m_maxIJKSubzoneSize; ___2090::ItemOffset_t const                            m_feSubzoneSize; bool const                                                 m_sortFENodesAndCells; std::vector<boost::shared_ptr<___1881> >               m_ijkZoneInfos; std::vector<std::vector<boost::shared_ptr<___1881> > > m_ijkZonePartitionInfos; std::vector<boost::shared_ptr<___1350> >                m_feZoneInfos; std::vector<std::vector<boost::shared_ptr<___1350> > >  m_feZonePartitionInfos; template<typename ZoneInfoType> void storeForSharedZones( std::vector<boost::shared_ptr<ZoneInfoType> >& zoneInfos, boost::shared_ptr<ZoneInfoType>                zoneInfo, ___4636                                    zone, ___4636                                    ___341); template <typename ZoneInfoType> void storeForSharedPartitions( std::vector<std::vector<boost::shared_ptr<ZoneInfoType> > >& zoneInfos, boost::shared_ptr<ZoneInfoType> zoneInfo, ___4636 zone, ___4636 ___341, ___4636 ___2977); }; }}
